### ISSUE TITLE
Do you plan to include a build script?

### ISSUE THREAD

**Issue by hillscottc** [rwieruch/minimal-react-webpack-babel-setup#1]
Great webpack 2 config. Do you have a build script also, that fills that dist dir?

**Comment by rwieruch** [comment]
Would be a good idea. Would you add a minimal approach in a PR?

**Comment by aitchnyu** [comment]
I second this. No reason a boilerplate shouldn't be production-ready.

**Comment by rwieruch** [comment]
Would you like to add a minimal PR @aitchnyu ? :)
