### ISSUE TITLE
deployed on live server

### ISSUE THREAD

**Issue by constantinosergiou** [rwieruch/minimal-react-webpack-babel-setup#10]
hello @rwieruch ,
nice work and good tutorial but  i am facing some issues
on local  i make the neccesary  change for the build 
``` 
"scripts": {
		"dev": "webpack --mode development",
		"build": "webpack --mode production",
		"start": "webpack-dev-server --config ./webpack.config.js --mode development",
		"test": "echo \"No test specified\" && exit 0"
	},

```
but on live is not working here is the url http://react.myseminars.com.cy

**Comment by constantinosergiou** [comment]
is ok sorry i fixed i was having wrong path for bundle but i have another question for you 
this is on vps and is working but i have also a shared hosting how can i do it there?

thanks

**Comment by rwieruch** [comment]
How did you fix it @constantinosergiou ? :)

**Comment by constantinosergiou** [comment]
@rwieruch via .htaccess

**Comment by rwieruch** [comment]
Ah okay 👍
