### ISSUE TITLE
Remove /patch in webpack config entry

### ISSUE THREAD

**Issue by jonmarkprice** [rwieruch/minimal-react-webpack-babel-setup#11]
Hey love your blog post and this repo, thanks!

It looks like the new version of `react-hot-loader` doesn't need the `.../patch` entry point anymore:
https://github.com/rwieruch/minimal-react-webpack-babel-setup/blob/496a8c87e80e52e6bc9bd14f318fa64a1c8c7f38/webpack.config.js#L5

See https://github.com/gaearon/react-hot-loader#no-patch-required

I removed it and it worked for me.

Cheers!

**Comment by rwieruch** [comment]
Oh nice. Did this came with a new release? 

If you have time, you could open a Pull Request for it! Optionally the tutorial can be adjusted over her as well: https://github.com/rwieruch/blog_robinwieruch_content/blob/master/minimal-react-webpack-babel-setup.md

**Comment by jonmarkprice** [comment]
Sure.
Looks like it was v4. Here's the commit for the README update: https://github.com/gaearon/react-hot-loader/commit/64da47ccbcd54585bc0a5788f8308d8062d88b35
