### ISSUE TITLE
package-lock.json

### ISSUE THREAD

**Issue by sbreiler** [rwieruch/minimal-react-webpack-babel-setup#13]
Hi, great work on the boilerplate. I'm just curious, is the file "package-lock.json" needed in youre repo or should it be removed?

**Comment by rwieruch** [comment]
Yes, it's recommended to add lock files (npm, yarn, ...) to version control. See https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5 for some explanation.
