### ISSUE TITLE
new @babel packages

### ISSUE THREAD

**Issue by danosaure** [rwieruch/minimal-react-webpack-babel-setup#14]
Can you update your documentation to include the new `@babel/*` packages?

Thanks,

**Comment by rwieruch** [comment]
I don't know what you mean? A link would be appreciated :)

**Comment by danosaure** [comment]
I was getting errors when running the example. I had to update the packages to: `@babel/core`, `@babel/preset-env`, etc...

**Comment by rwieruch** [comment]
Ok, that's something new. Anyone else having this problem?

**Comment by tuomaz** [comment]
I also have these problems. I think babel-loader depends on Babel 7, and Babel 7 has renamed all Babel packages.

**Comment by tuomaz** [comment]
Something like this works for me: https://pastebin.com/UriSuW5p (please excuse me for not doing proper diffs or a PR)

**Comment by rwieruch** [comment]
Thanks for reporting it! I would love to adjust the tutorial. Has anyone a link where these breaking changes were announced?

**Comment by danosaure** [comment]
I didn't follow those announcements, but it's really because you just install the latest version of the libraries... which is the goal of the article (single place to have the latest...)

There is a migration guide: https://babeljs.io/docs/en/v7-migration

**Comment by rwieruch** [comment]
Thanks everyone for making me notice this! Updated the repo over here: https://github.com/rwieruch/minimal-react-webpack-babel-setup/commit/553a28a6b563f1088e003d7026f7d13fafa8557e
