### ISSUE TITLE
index.html page in dist folder cannot be opened without a local server

### ISSUE THREAD

**Issue by DomDumont** [rwieruch/minimal-react-webpack-babel-setup#17]
Hi,
Thanks for your boilerplate.
if you add a dot before '/bundle.js' we will be able open the html file directly (without a local server)

Please do 
<script src="./bundle.js"></script>
instead of 
<script src="/bundle.js"></script>

Thanks

**Comment by rwieruch** [comment]
Thanks for reporting this. Can you open a PR for it? :)

**Comment by DomDumont** [comment]
Sure, it's done. Have a nice day

**Comment by rwieruch** [comment]
Thank you :)
