### ISSUE TITLE
Getting an error while using it in codesandbox.io

### ISSUE THREAD

**Issue by murtraja** [rwieruch/minimal-react-webpack-babel-setup#18]
I was trying out this setup with [codesanbox.io](https://codesandbox.io/s/733lj9r0vq) but it throws an error. Do you have any ideas why this might be the case?

Thanks

P.S. the error is:
```
Invariant Violation
Target container is not a DOM element.
▶ 3 stack frames were collapsed.
evaluate
/src/index.js:6

  3 | 
  4 | const title = 'My Minimal React Webpack Babel Setup';
  5 | 
> 6 | ReactDOM.render(
  7 |   <div>{title}</div>,
  8 |   document.getElementById('app')
  9 | );
```

**Comment by rwieruch** [comment]
Checkout the id attribute in your .html file. Maybe it's not app, but root or something else: `<div id="root" />`

**Comment by murtraja** [comment]
Thanks for the quick reply. When I searched for this error, the top answer was indeed the name conflict. But unfortunately, that doesn't seem to be the case :(

P.S. If you click on the link in my previous comment, it will take you directly to the code as well as the error

**Comment by murtraja** [comment]
It turns out that webpack can't be configured with codesandbox. 
Thanks for looking into this. 
Closing the issue.
