### ISSUE TITLE
What about CSS, images and fonts ?

### ISSUE THREAD

**Issue by alamenai** [rwieruch/minimal-react-webpack-babel-setup#29]
Hi @rwieruch,

Thank you for the content and the setup you've created but I see that this configuration even it's **minimal** needs some Webpack plugin to handle images, CSS, and fonts to make more useful.

**Comment by rwieruch** [comment]
Sure. Please check these additions over here https://github.com/rwieruch/minimal-react-webpack-babel-setup#diy-add-ons and here https://github.com/rwieruch/minimal-react-webpack-babel-setup#alternatives in the Readme.
