### ISSUE TITLE
unexpected token on <div> tag

### ISSUE THREAD

**Issue by indefinitelee** [rwieruch/minimal-react-webpack-babel-setup#7]
just followed the setup and am getting this error.

any suggestions on how to resolve?

![screen shot 2018-03-21 at 3 36 59 pm](https://user-images.githubusercontent.com/20348276/37733993-402b7cfe-2d20-11e8-9207-680b559b1c88.png)

index.js
```
import React from 'react';
import ReactDOM from 'react-dom';

const title = 'My Minimal React Webpack Babel Setup';

ReactDOM.render(
  <div>{title}</div>,
  document.getElementById('app')
);

module.hot.accept();
```

update:
works if you remove the div brackets and {} around `title`

**Comment by rwieruch** [comment]
I guess your Webpack is not aware of React JSX by using Babel. You would need to check again your Babel configuration and your Webpack loaders for .js/. files

*.babelrc*

```
{
  "presets": [
    "env",
    "react",
    "stage-2"
  ]
}
```

*webpack.config.js*

```
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      }
    ]
  },
```

**Comment by indefinitelee** [comment]
arg i just had a typo in the filename of my **.bablerc** file. 

Thanks for the response and the tutorials.
